// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionBadge': string;
  'actionDelete': string;
  'actionDuplicate': string;
  'actionSearch': string;
  'actionSwap': string;
  'chartSection': string;
  'emptyState': string;
  'filterBar': string;
  'filterButton': string;
  'filterButtonActive': string;
  'filterLabel': string;
  'loading': string;
  'sortIndicator': string;
  'spaceFreed': string;
  'statDivider': string;
  'statItem': string;
  'statLabel': string;
  'statValue': string;
  'statsBar': string;
  'table': string;
  'tableCell': string;
  'tableHeader': string;
  'tableHeaderActive': string;
  'tableRow': string;
  'totalSaved': string;
  'totalSavedLabel': string;
  'totalSavedValue': string;
}
export const cssExports: CssExports;
export default cssExports;
