// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'barFill': string;
  'barLabel': string;
  'barRow': string;
  'barTrack': string;
  'barValue': string;
  'bars': string;
  'chart': string;
  'chartTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
