// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fieldGroup': string;
  'fieldHint': string;
  'fieldLabel': string;
  'numberInput': string;
  'row': string;
  'selectInput': string;
  'separator': string;
  'tagsInput': string;
  'textInput': string;
  'toggle': string;
  'toggleRow': string;
  'toggleSlider': string;
}
export const cssExports: CssExports;
export default cssExports;
