// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionDelete': string;
  'actionEnforce': string;
  'actionFlag': string;
  'addButton': string;
  'deleteButton': string;
  'editButton': string;
  'emptyHint': string;
  'emptyState': string;
  'loading': string;
  'ruleActionBadge': string;
  'ruleCard': string;
  'ruleControls': string;
  'ruleInfo': string;
  'ruleName': string;
  'ruleSummary': string;
  'rulesList': string;
  'toggle': string;
  'toggleSlider': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
