// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'card': string;
  'cardActions': string;
  'cardTitle': string;
  'cards': string;
  'currentSize': string;
  'dismissAllButton': string;
  'dismissButton': string;
  'emptyHint': string;
  'emptyState': string;
  'estimatedSize': string;
  'loading': string;
  'qualityValue': string;
  'savings': string;
  'sizeRow': string;
  'suggestedQuality': string;
  'swapButton': string;
  'toolbar': string;
  'toolbarTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
