// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonRow': string;
  'checkboxLabel': string;
  'formGroup': string;
  'inputWrapper': string;
  'label': string;
  'loading': string;
  'passwordWrapper': string;
  'saveButton': string;
  'section': string;
  'sectionHeader': string;
  'testButton': string;
  'testFailure': string;
  'testResult': string;
  'testSuccess': string;
  'textInput': string;
  'togglePasswordButton': string;
}
export const cssExports: CssExports;
export default cssExports;
