// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bestTag': string;
  'emptyState': string;
  'expandIcon': string;
  'expandIconOpen': string;
  'group': string;
  'groupActions': string;
  'groupCount': string;
  'groupHeader': string;
  'groupTitle': string;
  'groups': string;
  'keepBestButton': string;
  'keepSmallestButton': string;
  'loading': string;
  'row': string;
  'rowBitrate': string;
  'rowCodec': string;
  'rowHeader': string;
  'rowPath': string;
  'rowQuality': string;
  'rowRadio': string;
  'rowSize': string;
  'rows': string;
  'smallestTag': string;
}
export const cssExports: CssExports;
export default cssExports;
